### GET request to example server
POST http://localhost/mail/
Content-Type: application/json

{
  "name": "Vincent Wochnik",
  "email": "v.wochnik@gmail.com",
  "subject": "Test",
  "message": "Hello World!"
}